// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxahemerhoapxqfussfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4YWhlbWVyaG9hcHhxZnVzc2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTk2NTYsImV4cCI6MjA1OTI3NTY1Nn0.2bVF9HcdMekfGak-BleceuEyIPHmBkhFnf7yyENBAyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);